export const CustomerService = {
    getData() {
        return [
            {
                id: 1,
                name: 'Raju',
                email: 'raju@gamil.com',
                job: 'Business Analyst',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Open to work',
                rewards: '1',
            },
            {
                id: 2,
                name: 'Vignesh',
                email: 'vignesh@gamil.com',
                job: 'Quality Analyst',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Closed',
                rewards: '2',
            },
            {
                id: 3,
                name: 'Pradeep',
                email: 'pradeep@gamil.com',
                job: 'Developer',
                mobile: '9876543210',
                employability: '5 Weeks',
                status: 'Open to work',
                rewards: '3',
            },
            {
                id: 4,
                name: 'Dinesh',
                email: 'dinesh@gamil.com',
                job: 'Senior Developer',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Open to work',
                rewards: '4',
            },
            {
                id: 5,
                name: 'Jeeva',
                email: 'jeeva@gamil.com',
                job: 'Node Js Developer',
                mobile: '9876543210',
                employability: '3 Weeks',
                status: 'Open to work',
                rewards: '5',
            },
            {
                id: 6,
                name: 'Manikandan',
                email: 'Mani@gamil.com',
                job: 'Quality Analyst',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Closed',
                rewards: '1',
            },
            {
                id: 7,
                name: 'Raju',
                email: 'raju@gamil.com',
                job: 'Business Analyst',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Open to work',
                rewards: '1',
            },
            {
                id: 8,
                name: 'Vignesh',
                email: 'vignesh@gamil.com',
                job: 'Quality Analyst',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Closed',
                rewards: '2',
            },
            {
                id: 9,
                name: 'Pradeep',
                email: 'pradeep@gamil.com',
                job: 'Developer',
                mobile: '9876543210',
                employability: '5 Weeks',
                status: 'Open to work',
                rewards: '3',
            },
            {
                id: 10,
                name: 'Dinesh',
                email: 'dinesh@gamil.com',
                job: 'Senior Developer',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Open to work',
                rewards: '4',
            },
            {
                id: 11,
                name: 'Jeeva',
                email: 'jeeva@gamil.com',
                job: 'Node Js Developer',
                mobile: '9876543210',
                employability: '3 Weeks',
                status: 'Open to work',
                rewards: '5',
            },
            {
                id: 12,
                name: 'Manikandan',
                email: 'Mani@gamil.com',
                job: 'Quality Analyst',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Closed',
                rewards: '1',
            },
            {
                id: 13,
                name: 'Raju',
                email: 'raju@gamil.com',
                job: 'Business Analyst',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Open to work',
                rewards: '1',
            },
            {
                id: 14,
                name: 'Vignesh',
                email: 'vignesh@gamil.com',
                job: 'Quality Analyst',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Closed',
                rewards: '2',
            },
            {
                id: 15,
                name: 'Pradeep',
                email: 'pradeep@gamil.com',
                job: 'Developer',
                mobile: '9876543210',
                employability: '5 Weeks',
                status: 'Open to work',
                rewards: '3',
            },
            {
                id: 16,
                name: 'Dinesh',
                email: 'dinesh@gamil.com',
                job: 'Senior Developer',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Open to work',
                rewards: '4',
            },
            {
                id: 17,
                name: 'Jeeva',
                email: 'jeeva@gamil.com',
                job: 'Node Js Developer',
                mobile: '9876543210',
                employability: '3 Weeks',
                status: 'Open to work',
                rewards: '5',
            },
            {
                id: 18,
                name: 'Manikandan',
                email: 'Mani@gamil.com',
                job: 'Quality Analyst',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Closed',
                rewards: '1',
            },
            {
                id: 19,
                name: 'Raju',
                email: 'raju@gamil.com',
                job: 'Business Analyst',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Open to work',
                rewards: '1',
            },
            {
                id: 20,
                name: 'Vignesh',
                email: 'vignesh@gamil.com',
                job: 'Quality Analyst',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Closed',
                rewards: '2',
            },
            {
                id: 21,
                name: 'Pradeep',
                email: 'pradeep@gamil.com',
                job: 'Developer',
                mobile: '9876543210',
                employability: '5 Weeks',
                status: 'Open to work',
                rewards: '3',
            },
            {
                id: 22,
                name: 'Dinesh',
                email: 'dinesh@gamil.com',
                job: 'Senior Developer',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Open to work',
                rewards: '4',
            },
            {
                id: 23,
                name: 'Jeeva',
                email: 'jeeva@gamil.com',
                job: 'Node Js Developer',
                mobile: '9876543210',
                employability: '3 Weeks',
                status: 'Open to work',
                rewards: '5',
            },
            {
                id: 24,
                name: 'Manikandan',
                email: 'Mani@gamil.com',
                job: 'Quality Analyst',
                mobile: '9876543210',
                employability: '4 Weeks',
                status: 'Closed',
                rewards: '1',
            },
        ];
    },

    getCustomersSmall() {
        return Promise.resolve(this.getData().slice(0, 10));
    },

    getCustomersMedium() {
        return Promise.resolve(this.getData().slice(0, 50));
    },

    getCustomersLarge() {
        return Promise.resolve(this.getData().slice(0, 200));
    },

    getCustomersXLarge() {
        return Promise.resolve(this.getData());
    },

    getCustomers(params) {
        const queryParams = params
            ? Object.keys(params)
                .map((k) => encodeURIComponent(k) + '=' + encodeURIComponent(params[k]))
                .join('&')
            : '';

        return fetch('https://www.primefaces.org/data/customers?' + queryParams).then((res) => res.json());
    }
};
